default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: phone-book_development

test:
  <<: *default
  database: phone-book_test
production:
  <<: *default
  database: phone-book_production
  username: phone-book
  password: <%= ENV['PHONE-BOOK_DATABASE_PASSWORD'] %>
